## 4. 사이킷런 활용하기

사이킷런(scikit-learn)

파이썬을 활용한 머신러닝 도구

데이터 분석(예측)을 위한 간단하고 효율적인 도구

누구나 쉽게 다양한 상황에서 활용 가능

오픈 소스

사이킷 런으로 할 수 있는 일

분류(ex. 스팸메일 분류)

회귀(ex. 주택 가격 예측)

클러스터링(ex. 고객 분류)

차원축소(ex. 변수(컬럼)의 수를 줄임)

모델 선택(모델의 성능을 평가)

전처리(데이터 가공/변환)

In [63]:
import pandas as pd
import numpy as np
data = pd.DataFrame({
    '메뉴': ['[인기]아이펠치킨','닭강정','간장치킨','마늘치킨','파닭','승일양념치킨','양념반후라이드반','황금후라이드','[베스트]풀잎치킨'],
    '가격': [16000,15000,14000,14000,14000,13000,13000,12000,9900],
    '호수' : [11,12,9,9,11,10,10,10,10],
    '칼로리' : [1200.0,1500.0,1600.0,1800.0,1300.0,1400.0,1300.0,1000.0,1000.0],
    '할인율' : [0.5,0.2,0.2,0.2,0.2,0.2,0.2,0.2,np.nan],
    '할인가' : [8000.0,12000.0,11200.0,11200.0,11200.0,10400.0,10400.0,9600.0,np.nan],
    '원산지' : ['국내산','브라질','국내산','국내산','브라질','국내산','국내산','국내산','국내산'],
    '살찔까요' : ['no','yes','yes','yes','yes','yes','yes','no','no'],
    '고민' : ['무조건먹자','먹지말자','먹지말자','먹지말자','먹지말자','먹지말자','먹지말자','무조건먹자','무조건먹자']
})
data.to_csv('final_modudak.csv', index=False)
data

메뉴     가격  호수     칼로리  할인율      할인가  원산지 살찔까요     고민
0  [인기]아이펠치킨  16000  11  1200.0  0.5   8000.0  국내산   no  무조건먹자
1        닭강정  15000  12  1500.0  0.2  12000.0  브라질  yes   먹지말자
2       간장치킨  14000   9  1600.0  0.2  11200.0  국내산  yes   먹지말자
3       마늘치킨  14000   9  1800.0  0.2  11200.0  국내산  yes   먹지말자
4         파닭  14000  11  1300.0  0.2  11200.0  브라질  yes   먹지말자
5     승일양념치킨  13000  10  1400.0  0.2  10400.0  국내산  yes   먹지말자
6   양념반후라이드반  13000  10  1300.0  0.2  10400.0  국내산  yes   먹지말자
7     황금후라이드  12000  10  1000.0  0.2   9600.0  국내산   no  무조건먹자
8  [베스트]풀잎치킨   9900  10  1000.0  NaN      NaN  국내산   no  무조건먹자

In [64]:
# 데이터 변경
data.loc[2,'원산지'] = '미국'

In [65]:
df = data[['가격','호수','칼로리','원산지','살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [66]:
# 데이터 전처리 : 범주형 데이터

# 레이블 인코딩

# 원핫 인코딩

#type 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   가격      9 non-null      int64  
 1   호수      9 non-null      int64  
 2   칼로리     9 non-null      float64
 3   원산지     9 non-null      object 
 4   살찔까요    9 non-null      object 
dtypes: float64(1), int64(2), object(2)
memory usage: 488.0+ bytes


In [67]:
# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(df['원산지'])
le.transform(df['원산지'])

array([0, 2, 1, 0, 2, 0, 0, 0, 0])

In [68]:
#fit_transform
le.fit_transform(df['원산지'])

array([0, 2, 1, 0, 2, 0, 0, 0, 0])

In [69]:
# 데이터 변환
df['원산지'] = le.fit_transform(df['원산지'])
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0    0   no
1  15000  12  1500.0    2  yes
2  14000   9  1600.0    1  yes
3  14000   9  1800.0    0  yes
4  14000  11  1300.0    2  yes
5  13000  10  1400.0    0  yes
6  13000  10  1300.0    0  yes
7  12000  10  1000.0    0   no
8   9900  10  1000.0    0   no

In [70]:
# '살찔까요' 라벨 인코딩
df['살찔까요'] = le.fit_transform(df['살찔까요'])
df

가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

In [71]:
# 레이블 인코딩(심화) - 여러개 컬럼 한번에 인코딩
#활용할 데이터 선택

In [72]:
df = data[['가격','호수','칼로리','원산지','살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [73]:
# object 타입의 컬럼만 선택[원산지, 살찔까요]
# cols = ['원산지','살찔까요']
cols = df.select_dtypes(include='object').columns

In [74]:
# 한번에 레이블 인코딩
from sklearn.preprocessing import LabelEncoder
for col in cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])


In [75]:
#인코딩 결과 확인
df

가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

In [76]:
#원핫인코딩

In [77]:
# 활용할 데이터 선택
df = data[['가격','호수','칼로리','원산지','살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [78]:
#원핫인코딩
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False) #sparse=False : 희소행렬이 아닌 넘파이 배열로 반환
cat = ohe.fit_transform(df[['원산지']]) #대괄호 2번 해야 데이터프레임 형태호 반환

/Users/ralphpark/anaconda3/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [79]:
#원핫인코딩 결과 확인
cat

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [80]:
#카테코리
ohe.categories_

[array(['국내산', '미국', '브라질'], dtype=object)]

In [81]:
#피처(컬럼)이름과 카테고리 , 원래 카테고리 이름 활용
ohe.get_feature_names_out()

array(['원산지_국내산', '원산지_미국', '원산지_브라질'], dtype=object)

In [82]:
#원핫인코딩 결과를 데이터프레임으로 변환
df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out())
df_cat

원산지_국내산  원산지_미국  원산지_브라질
0      1.0     0.0      0.0
1      0.0     0.0      1.0
2      0.0     1.0      0.0
3      1.0     0.0      0.0
4      0.0     0.0      1.0
5      1.0     0.0      0.0
6      1.0     0.0      0.0
7      1.0     0.0      0.0
8      1.0     0.0      0.0

In [83]:
# 데이터 프레임 합치기
df = pd.concat([df,df_cat], axis=1)
df

가격  호수     칼로리  원산지 살찔까요  원산지_국내산  원산지_미국  원산지_브라질
0  16000  11  1200.0  국내산   no      1.0     0.0      0.0
1  15000  12  1500.0  브라질  yes      0.0     0.0      1.0
2  14000   9  1600.0   미국  yes      0.0     1.0      0.0
3  14000   9  1800.0  국내산  yes      1.0     0.0      0.0
4  14000  11  1300.0  브라질  yes      0.0     0.0      1.0
5  13000  10  1400.0  국내산  yes      1.0     0.0      0.0
6  13000  10  1300.0  국내산  yes      1.0     0.0      0.0
7  12000  10  1000.0  국내산   no      1.0     0.0      0.0
8   9900  10  1000.0  국내산   no      1.0     0.0      0.0

In [84]:
# 기존 컬럼 삭제
df = df.drop(['원산지'], axis=1)
df

가격  호수     칼로리 살찔까요  원산지_국내산  원산지_미국  원산지_브라질
0  16000  11  1200.0   no      1.0     0.0      0.0
1  15000  12  1500.0  yes      0.0     0.0      1.0
2  14000   9  1600.0  yes      0.0     1.0      0.0
3  14000   9  1800.0  yes      1.0     0.0      0.0
4  14000  11  1300.0  yes      0.0     0.0      1.0
5  13000  10  1400.0  yes      1.0     0.0      0.0
6  13000  10  1300.0  yes      1.0     0.0      0.0
7  12000  10  1000.0   no      1.0     0.0      0.0
8   9900  10  1000.0   no      1.0     0.0      0.0

In [85]:
# 원핫 인코딩 (심화) - 여러개 컬럼 한번에 인코딩

# 활용할 데이터 선택
df = data[['가격','호수','칼로리','원산지','살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [86]:
# 원핫인코딩
from sklearn.preprocessing import OneHotEncoder
cols = df.select_dtypes(include='object').columns
ohe = OneHotEncoder(sparse=False)
cat = ohe.fit_transform(df[cols])
df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out())
df_cat

/Users/ralphpark/anaconda3/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0      1.0     0.0      0.0      1.0       0.0
1      0.0     0.0      1.0      0.0       1.0
2      0.0     1.0      0.0      0.0       1.0
3      1.0     0.0      0.0      0.0       1.0
4      0.0     0.0      1.0      0.0       1.0
5      1.0     0.0      0.0      0.0       1.0
6      1.0     0.0      0.0      0.0       1.0
7      1.0     0.0      0.0      1.0       0.0
8      1.0     0.0      0.0      1.0       0.0

In [87]:
# 데이터 프레임 합치기
df = pd.concat([df,df_cat], axis=1)

In [88]:
df.head()

가격  호수     칼로리  원산지 살찔까요  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0  국내산   no      1.0     0.0      0.0      1.0       0.0
1  15000  12  1500.0  브라질  yes      0.0     0.0      1.0      0.0       1.0
2  14000   9  1600.0   미국  yes      0.0     1.0      0.0      0.0       1.0
3  14000   9  1800.0  국내산  yes      1.0     0.0      0.0      0.0       1.0
4  14000  11  1300.0  브라질  yes      0.0     0.0      1.0      0.0       1.0

In [89]:
# 기존 컬럼 삭제
df = df.drop(cols, axis=1)

In [90]:
df.head()

가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0      1.0     0.0      0.0      1.0       0.0
1  15000  12  1500.0      0.0     0.0      1.0      0.0       1.0
2  14000   9  1600.0      0.0     1.0      0.0      0.0       1.0
3  14000   9  1800.0      1.0     0.0      0.0      0.0       1.0
4  14000  11  1300.0      0.0     0.0      1.0      0.0       1.0

In [91]:
#[tip] 원핫인코딩 : 판다스 활용

In [92]:
# 활용할 데이터 선택
df = data[['가격','호수','칼로리','원산지','살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [93]:
# 판다스 원핫인코딩 - 판다스로 하는게 가장 간단하다
df = pd.get_dummies(df)

In [94]:
df

가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0        1       0        0        1         0
1  15000  12  1500.0        0       0        1        0         1
2  14000   9  1600.0        0       1        0        0         1
3  14000   9  1800.0        1       0        0        0         1
4  14000  11  1300.0        0       0        1        0         1
5  13000  10  1400.0        1       0        0        0         1
6  13000  10  1300.0        1       0        0        0         1
7  12000  10  1000.0        1       0        0        1         0
8   9900  10  1000.0        1       0        0        1         0

# 데이터 전처리 : 수치형 데이터

표준화

정규화(min-max)

표준화(standardScaler)

- 평균이 0과 분산이 1인 정규분포로 변환

- 16000(가격), 11(호수) 등을 그대로 적어도 되지만 머신러닝을 실행하면 데이터 표준화에 따라 결과 및 속도가 달라질 수 있다.

In [99]:
# 원핫인코딩 된 데이터
df.head()

가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0        1       0        0        1         0
1  15000  12  1500.0        0       0        1        0         1
2  14000   9  1600.0        0       1        0        0         1
3  14000   9  1800.0        1       0        0        0         1
4  14000  11  1300.0        0       0        1        0         1

In [100]:
# StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(df[['가격']])

array([[ 1.54246993],
       [ 0.94150762],
       [ 0.34054531],
       [ 0.34054531],
       [ 0.34054531],
       [-0.260417  ],
       [-0.260417  ],
       [-0.86137931],
       [-2.12340016]])

In [104]:
# StandardScaler 여러 변수에 적용
cols = ['가격','호수','칼로리']
df[cols] = scaler.fit_transform(df[cols])
df

가격        호수       칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  1.542470  0.848875 -0.577920        1       0        0        1         0
1  0.941508  1.940285  0.622376        0       0        1        0         1
2  0.340545 -1.333946  1.022475        0       1        0        0         1
3  0.340545 -1.333946  1.822672        1       0        0        0         1
4  0.340545  0.848875 -0.177822        0       0        1        0         1
5 -0.260417 -0.242536  0.222277        1       0        0        0         1
6 -0.260417 -0.242536 -0.177822        1       0        0        0         1
7 -0.861379 -0.242536 -1.378118        1       0        0        1         0
8 -2.123400 -0.242536 -1.378118        1       0        0        1         0

민맥스(MinMaxScaler)

-0~1 사이의 값으로 변환(데이터 사이즈 축소)

In [105]:
# MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
cols = ['가격','호수','칼로리']
df[cols] = scaler.fit_transform(df[cols])
df

가격        호수    칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  1.000000  0.666667  0.250        1       0        0        1         0
1  0.836066  1.000000  0.625        0       0        1        0         1
2  0.672131  0.000000  0.750        0       1        0        0         1
3  0.672131  0.000000  1.000        1       0        0        0         1
4  0.672131  0.666667  0.375        0       0        1        0         1
5  0.508197  0.333333  0.500        1       0        0        0         1
6  0.508197  0.333333  0.375        1       0        0        0         1
7  0.344262  0.333333  0.000        1       0        0        1         0
8  0.000000  0.333333  0.000        1       0        0        1         0

In [106]:
# Q. 다음 df 변수에서 수치형 데이터 컬럼('가격', '호수', '칼로리')을 모두 표준화해주세요.
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df = pd.get_dummies(df)
cols = ['가격', '호수', '칼로리']
scaler = StandardScaler()
df[cols] = scaler.fit_transform(df[cols])
df

가격        호수       칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  1.542470  0.848875 -0.577920        1       0        0        1         0
1  0.941508  1.940285  0.622376        0       0        1        0         1
2  0.340545 -1.333946  1.022475        0       1        0        0         1
3  0.340545 -1.333946  1.822672        1       0        0        0         1
4  0.340545  0.848875 -0.177822        0       0        1        0         1
5 -0.260417 -0.242536  0.222277        1       0        0        0         1
6 -0.260417 -0.242536 -0.177822        1       0        0        0         1
7 -0.861379 -0.242536 -1.378118        1       0        0        1         0
8 -2.123400 -0.242536 -1.378118        1       0        0        1         0

사이킷런에서 제공하는 데이터 셋

유방암 데이터

In [1]:
# 사이킷런 데이터 불러오기
from sklearn.datasets import load_breast_cancer
dataset = load_breast_cancer()
dataset

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [2]:
# 피처 이름 확인
dataset.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [3]:
# 타겟 확인
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [4]:
# 데이터 확인
dataset.data[:3]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [6]:
# 데이터 프레임으로 변환
cancer_df = pd.DataFrame(data = dataset.data, columns=dataset.feature_names)
cancer_df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [7]:
# 타겟 추가하기
cancer_df['target'] = dataset.target
cancer_df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
0                  0.2654          0.4601                  0.11890       0  
1                  0.1860          0.2750                  0.08902       0  
2                  0.2430          0.3613                  0.08758       0  
3                  0.2575          0.6638                  0.17300       0  
4                  0.1625          0.2364                  0.076

In [8]:
# 데이터셋 확인(load_*)
import sklearn.datasets
sklearn.datasets.__all__

['clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_species_distributions',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_rcv1',
 'fetch_kddcup99',
 'fetch_openml',
 'get_data_home',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_breast_cancer',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_circles',
 'make_classification',
 'make_checkerboard',
 'make_friedman1',
 'make_friedman2',
 'make_friedman3',
 'make_gaussian_quantiles',
 'make_hastie_10_2',
 'make_low_rank_matrix',
 'make_moons',
 'make_multilabel_classification',
 'make_regression',
 'make_s_curve',
 'make_sparse_coded_signal',
 'make_sparse_spd_matrix',
 'make_sparse_uncorrelated',
 'make_spd_matrix',
 'make_swiss_roll']

In [9]:
# 당뇨병 데이터셋
# 당뇨병 데이터셋 불러오기
from sklearn.datasets import load_diabetes
dataset = load_diabetes()
dataset

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [11]:
# 피처 이름 확인
dataset.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [12]:
# 타겟 확인
dataset.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [13]:
# 데이터 확인
dataset.data[:3]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567042, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286131, -0.02593034]])

In [15]:
# 데이터 프레임으로 변환
diabetes_df = pd.DataFrame(data = dataset.data, columns=dataset.feature_names)
diabetes_df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [16]:
# 타겟 추가하기
diabetes_df['target'] = dataset.target
diabetes_df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019907 -0.017646   151.0  
1   -0.039493 -0.068332 -0.092204    75.0  
2   -0.002592  0.002861 -0.025930   141.0  
3    0.034309  0.022688 -0.009362   206.0  
4   -0.002592 -0.031988 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018114  0.044485   104.0  
439 -0.011080 -0.046883  0.015491   132.0  
440  0.026560  0.044529 -0.025930   220.0  
441 -0.039493 -0.004222  0.003064    57.0  

[442 rows x 11 columns]

머신러닝 : 분류

검증데이터 분리

In [29]:
# 검증데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(cancer_df.drop('target', axis=1),cancer_df['target'], test_size=0.3, random_state=1004) # random_state는 매번 같은 곳에서 분리하는 역할.그래야 모델도 평가가 가능함

수업에서 설명한 데이터 분리 예시

총 4개의 데이터가 나온다


        학습_비율(7)    테스트_비율(3)

데이터(X)  x_train()    x_test()

타겟(y)   y_train()    y_test()


In [30]:
# train 데이터 확인(X)
X_train.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
350       11.660         17.07           73.70      421.0          0.07561   
384       13.280         13.72           85.79      541.8          0.08363   
7         13.710         20.83           90.20      577.9          0.11890   
557        9.423         27.88           59.26      271.3          0.08123   
49        13.490         22.30           86.91      561.0          0.08752   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
350           0.03630        0.008306              0.01162         0.1671   
384           0.08575        0.050770              0.02864         0.1617   
7             0.16450        0.093660              0.05985         0.2196   
557           0.04971        0.000000              0.00000         0.1742   
49            0.07698        0.047510              0.03384         0.1809   

     mean fractal dimension  ...  worst radius  worst texture  \
350                 0.05731  ...         13.28          19.74   
384                 0.05594  ...         14.24          17.37   
7                   0.07451  ...         17.06          28.14   
557                 0.06059  ...         10.49          34.24   
49                  0.05718  ...         15.15          31.82   

     worst perimeter  worst area  worst smoothness  worst compactness  \
350            83.61       542.5           0.09958            0.06476   
384            96.59       623.7           0.11660            0.26850   
7             110.60       897.0           0.16540            0.36820   
557            66.50       330.6           0.10730            0.07158   
49             99.00       698.8           0.11620            0.17110   

     worst concavity  worst concave points  worst symmetry  \
350          0.03046               0.04262          0.2731   
384          0.28660               0.09173          0.2736   
7            0.26780               0.15560          0.3196   
557          0.00000               0.00000          0.2475   
49           0.22820               0.12820          0.2871   

     worst fractal dimension  
350                  0.06825  
384                  0.07320  
7                    0.11510  
557                  0.06969  
49                   0.06917  

[5 rows x 30 columns]

In [31]:
# 학습 데이터 확인(y)
y_train.head()

350    1
384    1
7      0
557    1
49     1
Name: target, dtype: int64

In [32]:
# 데이터 크기
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((398, 30), (171, 30), (398,), (171,))

의사결정 나무(Descision Tree)

In [38]:
# 머신러닝(분류)
from sklearn.tree import DecisionTreeClassifier
# 모델선택
model = DecisionTreeClassifier()
# 학습
model.fit(X_train,y_train)
# 예측
pred = model.predict(X_test)
pred

array([1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

평가(accuarcy)

In [37]:
# 정확도 accuarcy_score(실제값, 예측값)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.8947368421052632

머신러닝: 회귀

In [39]:
# 검증데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(diabetes_df.drop('target', axis=1),diabetes_df['target'], test_size=0.3, random_state=1004)

In [40]:
# train 데이터 확인(X)
X_train.head()

age       sex       bmi        bp        s1        s2        s3  \
232  0.012648  0.050680  0.000261 -0.011420  0.039710  0.057245 -0.039719   
81   0.012648  0.050680 -0.022373 -0.029770  0.010815  0.028435 -0.021311   
227  0.067136  0.050680 -0.029918  0.057437 -0.000193 -0.015719  0.074412   
334 -0.060003  0.050680 -0.047163 -0.022885 -0.071743 -0.057681 -0.006584   
83  -0.038207 -0.044642  0.009961 -0.046985 -0.059359 -0.052983 -0.010266   

           s4        s5        s6  
232  0.056081  0.024055  0.032059  
81   0.034309 -0.006081 -0.001078  
227 -0.050564 -0.038460  0.007207  
334 -0.039493 -0.062917 -0.054925  
83  -0.039493 -0.015999 -0.042499

In [42]:
# 학습 데이터 확인(y)
y_train.head()

232    259.0
81      51.0
227    108.0
334     72.0
83     210.0
Name: target, dtype: float64

In [43]:
# 데이터 크기
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((309, 10), (133, 10), (309,), (133,))

선형회귀(Linear Regression)

In [44]:
# 머신러닝(회귀)
from sklearn.linear_model import LinearRegression
# 모델선택
model = LinearRegression()
# 학습
model.fit(X_train,y_train)
# 예측
pred = model.predict(X_test)
pred

array([128.42468606, 135.08774266, 154.78504343, 106.09306564,
       149.54478558, 165.32708009, 140.29166154, 167.9600165 ,
        69.44851384, 189.42811434, 144.98692247, 150.10700196,
       211.15983244, 108.59257071, 160.3856331 , 154.09855476,
       198.78116874, 101.16062264, 165.82852734, 196.03659567,
       147.16472505, 108.25668788, 207.27889551, 127.53191954,
       181.85997027, 228.49975565,  86.59589481, 155.35081963,
       182.49593133, 182.96390209, 207.63119699, 199.81134435,
       157.35809543,  61.82465786,  88.11634158,  95.75033061,
       134.03120864,  85.95903914, 177.69650387, 249.40014721,
       171.77206628, 204.71572412, 239.12149428,  89.24927278,
       244.20385113, 180.36498587, 161.10608699, 119.14846149,
       102.81815844, 153.35400825, 129.06743815, 208.80206598,
       107.93927973, 138.81355171, 166.04217088,  86.04455248,
       181.03094575, 117.97907348,  79.04947426, 127.20387612,
       194.05986421, 205.13463546, 233.84790901,  48.53

평가(mean_squared_error)

In [46]:
# 정확도 mean_squared_error(실제값, 예측값)
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, pred)
# 결과값이 낮으면 낮을수록 좋다

3229.454787929743

공식문서 소개

바로가기 : https://scikit-learn.org/stable/

튜토리얼을 통해 어떻게 확인하는지 알수 있다.

In [47]:
# 종합퀴즈
# Q. 처음 만들었던 'final_modudak.csv' 데이터로 치킨 가격 예측을 하는 회귀 모델을 만들어보겠습니다.
# 빈칸을 채워주세요.

# 데이터 로드
data = pd.read_csv('final_modudak.csv')

# 모델에 사용할 칼럼 지정
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()

# 원핫인코딩
df = pd.get_dummies(df)

# test데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df.drop('가격', axis=1), df['가격'], test_size=0.3, random_state=1004)

# 머신러닝(회귀)
# 원하는 모델 라이브러리를 불러오세요.
from sklearn.linear_model import LinearRegression

# 원하는 모델을 선택해 보세요.
model = LinearRegression()

# 학습
model.fit(X_train,y_train)

# 예측
pred = model.predict(X_test)

# test데이터의 실제값과 예측값 비교
pd.DataFrame({'실제값' : y_test, '예측값' : pred})

실제값      예측값
0  16000  12750.0
6  13000  12812.5
8   9900  12000.0

In [48]:
# Q. 위에서 만든 모델의 평가지표를 확인해보세요.
# 평가지표 : mean_squared_error
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, pred)


5002552.083333338