## 딥러닝 한번에 끝내기
### 2. 텐서 표현과 연산

### 2-1 들어가며

1. tensor
2. tensor 타입 및 변환
3. tensor 연산

학습목표

텐서의 개념을 이해합니다.

텐서의 데이터 타입을 이해합니다.

텐서의 연산을 수행합니다.

## 2-2 텐서(Tensor)

![](./img02/01.png)

2차원의 텐서는 축이 2개라 rank 2 텐서라고 부릅니다.

4차원 텐서는 기존 3차원 텐서의 축 3개 외 추가적인 축 1개가 더 생겨 rank 4 텐서라고 부릅니다.

6차원을 넘는 다양한 텐서가 존재


![](./img02/02.png)

3차원 텐서의 대표적인 데이터는 주가 데이터

![](./img02/03.png)

컬러 이미지가 여러장이면 영상데이터 저장 가능

## 0D Tensor(Scalar)

In [52]:
import tensorflow as tf

#0차원 텐서는 하나의 숫자를 담고 있는 텐서(tensor)입니다. 스칼라(scalar)라고도 부르며, 축과 형상이 없습니다.

# tf.constant()를 사용하면 상수(constant) 텐서를 만들 수 있고, 만든 텐서에 tf.rank()를 적용하면 축의 개수를 알 수 있습니다.

t0 = tf.constant(1)
print(t0)
print(tf.rank(t0)) # rank는 축의 개수를 의미합니다.

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


## 1D Tensor(Vector)

In [53]:
t1 = tf.constant([1, 2, 3])
print(t1)
print(tf.rank(t1))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


## 2D Tensor(Matrix)

In [54]:
t2 = tf.constant([[1, 2, 3], [4, 5, 6]])
print(t2)
print(tf.rank(t2))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


## 3D Tensor

3차원 텐서는 큐브(cube)와 같은 모양으로 세개의 축이 존재하며, 일반적으로 데이터가 연속된 시퀀스 데이터나 시간 축이 포함된 시계열 데이터에 해당합니다. 주로 샘플(samples), 타임스텝(timesteps), 특성(features)을 가진 구조로 사용됩니다. 3차원 텐서를 이용하는 데이터로는 주식 가격 데이터셋, 시간에 따른 질병 발병 데이터 등이 존재합니다.

In [55]:
t3 = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [
                 10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print(t3)
print(tf.rank(t3))

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


## 4D Tensor

4차원 텐서는 4개의 축이 존재하며, 컬러 이미지 데이터가 대표적인 사례 (흑백 이미지 데이터는 3D Tensor로 가능)입니다. 주로 샘플(samples), 높이(height), 너비(width), 컬러 채널(channel)을 가진 구조로 사용됩니다.

In [56]:
t4 = tf.constant([[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [
                 10, 11, 12]], [[13, 14, 15], [16, 17, 18]]], [[[19, 20, 21], [22, 23, 24]], [[25, 26, 27], [28, 29, 30]], [[31, 32, 33], [34, 35, 36]]]])
print(t4)
print(tf.rank(t4))

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]]


 [[[19 20 21]
   [22 23 24]]

  [[25 26 27]
   [28 29 30]]

  [[31 32 33]
   [34 35 36]]]], shape=(2, 3, 2, 3), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


5D Tensor

5차원 텐서는 5개의 축이 존재하며, 비디오 데이터가 대표적인 사례입니다. 주로 샘플(samples), 프레임(frames), 높이(height), 너비(width), 컬러 채널(channel)을 가진 구조로 사용됩니다.

In [57]:
t5 = tf.constant([[[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [
                 10, 11, 12]], [[13, 14, 15], [16, 17, 18]]], [[[19, 20, 21], [22, 23, 24]], [[25, 26, 27], [28, 29, 30]], [[31, 32, 33], [34, 35, 36]]]], [[[[37, 38, 39], [40, 41, 42]], [[43, 44, 45], [
                     46, 47, 48]], [[49, 50, 51], [52, 53, 54]]], [[[55, 56, 57], [58, 59, 60]], [[61, 62, 63], [64, 65, 66]], [[67, 68, 69], [70, 71, 72]]]]])
print(t5)
print(tf.rank(t5))

tf.Tensor(
[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]

   [[13 14 15]
    [16 17 18]]]


  [[[19 20 21]
    [22 23 24]]

   [[25 26 27]
    [28 29 30]]

   [[31 32 33]
    [34 35 36]]]]



 [[[[37 38 39]
    [40 41 42]]

   [[43 44 45]
    [46 47 48]]

   [[49 50 51]
    [52 53 54]]]


  [[[55 56 57]
    [58 59 60]]

   [[61 62 63]
    [64 65 66]]

   [[67 68 69]
    [70 71 72]]]]], shape=(2, 2, 3, 2, 3), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


## 2-3 텐서의 데이터 타입 및 변환

![](./img02/04.png)

![](./img02/05.png)

## 텐서의 생성

In [58]:
# 상수 값 2인 텐서를 생성해 봅시다. 기본적으로 정수형 int32 타입을 가지는 것을 알 수 있습니다.
i = tf.constant(2)
print(i)

tf.Tensor(2, shape=(), dtype=int32)


In [59]:
# 상수 값 2.0으로 지정하면, 실수형 float32인 텐서를 생성합니다.
i = tf.constant(2.0)
print(i)

tf.Tensor(2.0, shape=(), dtype=float32)


In [60]:
# 문자열을 값으로 가지는 텐서를 생성할 수도 있으며, 타입은 string이 됩니다.
i = tf.constant('Hello, World!')
print(i)

tf.Tensor(b'Hello, World!', shape=(), dtype=string)


In [61]:
# 지정한 상수 값의 타입을 보고 자동으로 텐서 타입이 정해지는 것 외에도 필요한 텐서의 타입을 지정하여 생성할 수 있습니다. 여기서는 tf.float16으로 16비트 실수형으로 타입을 지정하였습니다.
f16 = tf.constant(2.0, dtype=tf.float16)
print(f16)

tf.Tensor(2.0, shape=(), dtype=float16)


In [62]:
# 그 밖에도 8비트의 정수형인 tf.int8을 지정하여 텐서를 생성할 수 있습니다. 직접 코드를 작성해 보세요.
i8 = tf.constant(2, dtype=tf.int8)
print(i8)

tf.Tensor(2, shape=(), dtype=int8)


## 텐서 변환

### 텐서 타입 변환

In [63]:
# 텐서의 타입을 변환하고자 할 때는 tf.cast를 사용합니다. 여기서는 16비트 실수형 tf.float16을 32비트 실수형 tf.float32로 변환하였습니다.
f32 = tf.cast(f16, dtype=tf.float32)
print(f32)

tf.Tensor(2.0, shape=(), dtype=float32)


In [64]:
# 다음 예제에서는 8비트 정수형 tf.int8을 32비트 정수형인 tf.int32로 변환하고자 합니다. 직접 코드를 작성해 보세요.
i32 = tf.cast(i8, dtype=tf.int32)
print(i32)

tf.Tensor(2, shape=(), dtype=int32)


### 텐서 형상 변환

In [65]:
# 텐서의 형상을 변환하는 것은 tf.reshape 함수를 통해 가능합니다. 이 함수는 텐서의 원소는 그대로 유지하면서 텐서의 구조를 바꿉니다.
x = tf.constant([[1], [2], [3]])
print(x)
print(x.shape)

y = tf.reshape(x, [1, 3])
print(y)
print(y.shape)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
(3, 1)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
(1, 3)


### 텐서 전치

In [66]:
# 텐서를 전치하여 형상을 바꾸는 역할로 tf.transpose 함수를 사용할 수 있습니다.
print(y)
print(tf.transpose(y))
print(y.shape)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
(1, 3)


### 차원압축

In [67]:
# 텐서에서 크기가 1인 차원을 제거하는 tf.squeeze 함수를 이용해 형상을 변경합니다.
print(x)
print(tf.squeeze(x))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


### 차원 추가

In [68]:
# 텐서의 차원을 추가하는 tf.expand_dims 함수를 이용해 형상을 변경합니다. 여기서 axis는 차원을 확장할 텐서의 축을 지정해주는 역할을 합니다.
print(y)
print(tf.expand_dims(y, axis=0))
print(tf.expand_dims(y, axis=1))
print(tf.expand_dims(y, axis=2))

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor([[[1 2 3]]], shape=(1, 1, 3), dtype=int32)
tf.Tensor([[[1 2 3]]], shape=(1, 1, 3), dtype=int32)
tf.Tensor(
[[[1]
  [2]
  [3]]], shape=(1, 3, 1), dtype=int32)


### 텐서 분리

In [69]:
# tf.split 함수를 이용하여 텐서의 지정한 차원을 기준으로 여러 개의 텐서로 구분합니다. 예제에서는 텐서 x를 3개로 분리한 것을 알 수 있습니다.
print(x)
print(tf.split(x, 3))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
[<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[1]], dtype=int32)>, <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[2]], dtype=int32)>, <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[3]], dtype=int32)>]


### 텐서 연결

In [70]:
# tf.concat 함수는 지정한 축 axis를 기준으로 텐서들을 이어붙입니다.
print(x)
print(tf.concat([x, x], axis=0))
print(tf.concat([x, x], axis=1))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]
 [1]
 [2]
 [3]], shape=(6, 1), dtype=int32)
tf.Tensor(
[[1 1]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int32)


### 2-4 텐서의 연산

![](./img02/06.png)


####0차원 텐서의 연산

In [71]:
# 먼저 더하기와 빼기 연산을 수행해보겠습니다. 더하기 연산자인 +와 빼기 연산자인 -를 이용해서 텐서간의 계산이 가능하고, add와 subtract 함수를 이용해서도 계산이 가능합니다.

print(tf.constant(2) + tf.constant(2))
print(tf.constant(2) - tf.constant(2))
print(tf.add(tf.constant(2), tf.constant(2)))
print(tf.subtract(tf.constant(2), tf.constant(2)))

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [72]:
# 곱하기와 나누기 연산도 *와 / 연산자를 이용하는 방법과 multiply와 divide 함수를 이용하는 방법이 있습니다.
print(tf.constant(2) * tf.constant(2))
print(tf.constant(2) / tf.constant(2))
print(tf.multiply(tf.constant(2), tf.constant(2)))
print(tf.divide(tf.constant(2), tf.constant(2)))

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float64)


In [73]:
# 텐서 연산에서 주의할 점은 서로 다른 타입을 가지는 텐서는 연산이 되지 않고, 에러가 발생한다는 점입니다.
print(tf.constant(2) + tf.constant(2.2))

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2] name: 

In [ ]:
# 다른 타입을 가지는 텐서는 연산을 위해서 타입을 변환해 주어야합니다. 2-3 스텝에서 언급했던 tf.cast를 사용하여 텐서의 타입을 서로 맞춰준 후에 연산을 할 수 있습니다.
print(tf.cast(tf.constant(2), tf.float32) + tf.constant(2.2))

#### 1차원 이상의 텐서 연산
0차원의 상수값만 존재하는 텐서 계산 외에도 1차원 이상의 텐서에 대해서도 연산이 가능합니다. 다만 텐서의 모양이 직사각형이거나 연산이 가능하도록 형상을 맞춰주어야 합니다.

In [ ]:
# 1차원 텐서 2개를 만들어 봅시다.
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])

In [ ]:
## Q. 사칙연산(더하기, 빼기, 곱하기, 나누기)을 해보세요.
print(x + y)
print(x - y)
print(x * y)
print(x / y)

#### 2차원 텐서의 연산

In [ ]:
# # Q. 크기 (2,2)인 2차원 텐서 2개를 생성해 보세요.
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

In [ ]:
# 텐서를 계산하기 위한 여러 연산자들을 제공하고 있으며, +, -, *, / 연산자는 요소별(element-wise) 연산을 수행하고, @ 연산자의 경우에는 행렬 곱 연산을 수행합니다.
# 텐서 연산은 연산자를 통해서도 가능하지만, 제공되는 함수를 통해서도 연산이 가능합니다.
print(a + b) # element-wise addition
print(a - b) # element-wise subtraction
print(a * b) # element-wise multiplication
print(a @ b) # matrix multiplication
print(a / b) # element-wise division

그 밖에도 유용한 여러 함수들이 존재합니다.

reduce_max(): 텐서 값 중에서 최대값을 계산합니다.

argmax(): 최대값의 위치를 반환합니다. 예제에서는 [4.0, 5.0, 6.0] 보다 [10.0, 9.0, 8.0]이 다 크기 때문에 [0 0 0]이 아니라 [1 1 1]의 결과를 보여주고 있습니다.

nn.softmax(): 텐서의 값을 0과 1 사이의 값으로 보여줍니다. 예제에서는 [4.0, 5.0, 6.0] 값이 [0.09003057 0.24472848 0.66524094]으로 변환되었고, [10.0, 9.0, 8.0]이 [0.66524094 0.24472848 0.09003057]로 변환되었습니다.

In [74]:
c = tf.constant([[4.0, 5.0, 6.0],
                 [10.0, 9.0, 8.0]])

print(tf.reduce_max(c))
print(tf.argmax(c))
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 1 1], shape=(3,), dtype=int64)
tf.Tensor(
[[0.09003057 0.24472848 0.66524094]
 [0.66524094 0.24472848 0.09003057]], shape=(2, 3), dtype=float32)


### 이번시간 정리
딥러닝의 기본 데이터 표현 방법인 텐서 개념을 이해했습니다.

텐서의 데이터 타입과 변환에 대한 원리를 이해했습니다.

텐서 간의 연산 방법이나 함수에 대해서 이해했습니다.

종합문제

In [75]:
# 아래 텐서를 각각 (2,2,2)의 형태를 가진 3차원 텐서로 만들고 행렬곱 연산을 해보세요.
a = tf.constant([1, 2, 3, 4, 5, 6, 7, 8], dtype=tf.float32) # float32로 dtype을 지정해줍니다.
b = tf.constant([[1., 2., 3., 4., 5., 6., 7., 8.]], dtype=tf.float32)

# Q. 위에 있는 2개의 텐서를 행렬곱연산이 가능하도록 3차원 텐서로 변환해주세요.
a = tf.reshape(a, (2, 2, 2))
b = tf.reshape(b, (2, 2, 2))

print(a@b)

tf.Tensor(
[[[  7.  10.]
  [ 15.  22.]]

 [[ 67.  78.]
  [ 91. 106.]]], shape=(2, 2, 2), dtype=float32)
